NATURAL_PATTERN = r'(0|[1-9][0-9]*)'
INTEGER_PATTERN = rf'-?{NATURAL_PATTERN}'
RATIONAL_PATTERN = rf'{INTEGER_PATTERN}/{NATURAL_PATTERN}'
POLYNOMIAL_PATTERN = rf'{RATIONAL_PATTERN}(; {RATIONAL_PATTERN})*'